In [1]:
import numpy as np

## 布尔型索引

In [2]:
names = np.array(['Bob', 'Joe',  'Will', 'Bob', 'Will', 'Joe',  'Joe'])

In [5]:
data = np.random.randn(7,4)

In [6]:
data

array([[-0.57933803,  1.30807342, -1.08887412,  1.2543035 ],
       [-0.49938617, -0.12218315,  0.99367904,  0.60902248],
       [-0.18453092,  1.47027956, -1.24025289, -1.85800601],
       [ 0.72974803, -0.29103159, -0.08768805, -0.86144262],
       [ 0.47381124, -1.05561609, -0.70384228,  0.01327028],
       [-0.86948077,  1.21227111,  0.17466712, -0.0680993 ],
       [ 1.2878203 , -1.13623617,  0.39841197,  0.66160558]])

In [7]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [9]:
data[names == 'Bob']

array([[-0.57933803,  1.30807342, -1.08887412,  1.2543035 ],
       [ 0.72974803, -0.29103159, -0.08768805, -0.86144262]])

In [10]:
data[names == 'Bob', 2:]

array([[-1.08887412,  1.2543035 ],
       [-0.08768805, -0.86144262]])

In [11]:
names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [13]:
data[~(names == 'Bob')]

array([[-0.49938617, -0.12218315,  0.99367904,  0.60902248],
       [-0.18453092,  1.47027956, -1.24025289, -1.85800601],
       [ 0.47381124, -1.05561609, -0.70384228,  0.01327028],
       [-0.86948077,  1.21227111,  0.17466712, -0.0680993 ],
       [ 1.2878203 , -1.13623617,  0.39841197,  0.66160558]])

In [14]:
mask = (names == 'Bob') | (names == 'Will')

In [15]:
data[mask]

array([[-0.57933803,  1.30807342, -1.08887412,  1.2543035 ],
       [-0.18453092,  1.47027956, -1.24025289, -1.85800601],
       [ 0.72974803, -0.29103159, -0.08768805, -0.86144262],
       [ 0.47381124, -1.05561609, -0.70384228,  0.01327028]])

In [16]:
data[ data <0 ]

array([-0.57933803, -1.08887412, -0.49938617, -0.12218315, -0.18453092,
       -1.24025289, -1.85800601, -0.29103159, -0.08768805, -0.86144262,
       -1.05561609, -0.70384228, -0.86948077, -0.0680993 , -1.13623617])

In [17]:
data[ data <0 ] = 0

In [18]:
data

array([[0.        , 1.30807342, 0.        , 1.2543035 ],
       [0.        , 0.        , 0.99367904, 0.60902248],
       [0.        , 1.47027956, 0.        , 0.        ],
       [0.72974803, 0.        , 0.        , 0.        ],
       [0.47381124, 0.        , 0.        , 0.01327028],
       [0.        , 1.21227111, 0.17466712, 0.        ],
       [1.2878203 , 0.        , 0.39841197, 0.66160558]])

## 花式索引

In [19]:
arr = np.empty((8,4))

In [20]:
for i in range(8):
    arr[i] = i

In [21]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [22]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [23]:
arr = np.arange(32).reshape((8,4))

In [24]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [25]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [26]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [27]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

## 数组转置和轴对换

In [28]:
arr = np.arange(15).reshape(3,5)

In [30]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [31]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [32]:
arr= np.random.randn(6,3)

In [34]:
np.dot(arr.T,arr)

array([[ 8.96010294, -4.63048026, -1.77058951],
       [-4.63048026,  9.75566823, -3.56114342],
       [-1.77058951, -3.56114342, 12.82396156]])